scons: fix configure with XML2_INCLUDES or XML2_LIBS
Checking if boost_regex was built with ICU unicode support... (cached) yes
ValueError: not enough values to unpack (expected 5, got 4):
  File "/var/tmp/portage/sci-geosciences/mapnik-3.0.23/work/mapnik-v3.0.23/SConstruct", line 1585:
    for libname, headers, required, lang, define in OPTIONAL_LIBSHEADERS:

HAVE_LIBXML2 is defined in src/build.py based on HAS_LIBXML2.