Upgrade to latest mapnik-vector-tile
D:\a\mapnik\mapnik\deps\mapbox\mapnik-vector-tile\src\vector_tile_projection.hpp(21): error C2065: 'M_PI': undeclared identifier
D:\a\mapnik\mapnik\deps\mapbox\mapnik-vector-tile\src\vector_tile_projection.hpp(21): error C2737: 'half_of_equator': const object must be initialized